name: code-quality

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install  black isort flake8
    - name: Code quality
      run: |
        set +e
        poetry run black --check --diff webapp; BLACK_CODE=$?
        poetry run isort --check-only --diff webapp; ISORT_CODE=$?
        poetry run flake8 --output-file=flake8-report.txt --tee webapp; FLAKE8_CODE=$?
        if [[ $BLACK_CODE -ne 0 || $ISORT_CODE -ne 0 || $FLAKE8_CODE -ne 0 ]]; then
          echo "SOME CHECKS HAVE FAILED"
          exit 1
        fi
        set -e
